#!/usr/bin/env python3
"""Generate one SEO landing page per church from churches.json.

Outputs:
  nha-tho/<slug>.html   one page per church (title: "Giờ Lễ {name} - {address}")
  assets/church.css     CSS shared by the generated pages (copied from index.html)
  sitemap.xml           static entries kept, church URLs regenerated
  scripts/church_pages.json  id -> {slug, hash, lastmod}; commit it so URLs never change
                        once published and lastmod only moves when a church's data does

Re-run after refreshing churches.json:  python3 scripts/gen_church_pages.py
"""
import hashlib
import html
import json
import re
import shutil
import unicodedata
from collections import defaultdict
from datetime import date
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parent.parent
SITE = "https://docs.thachnguyenhub.com"
OUT_DIR = ROOT / "nha-tho"
REGISTRY = ROOT / "scripts" / "church_pages.json"
PLAY_URL = "https://play.google.com/store/apps/details?id=com.buocchantheochua.app.prod"

# schedule.weekly keys follow the app: "0" = Chủ Nhật ... "6" = Thứ Bảy.
# Displayed Monday first, Sunday last.
# Every page lives in nha-tho/, so links are relative ("../assets/...") and work from file:// too;
# only canonical / og:url / sitemap use absolute SITE URLs.
DAYS = [("1", "Thứ Hai"), ("2", "Thứ Ba"), ("3", "Thứ Tư"), ("4", "Thứ Năm"),
        ("5", "Thứ Sáu"), ("6", "Thứ Bảy"), ("0", "Chủ Nhật")]

SITEMAP_MARK_START = "  <!-- church pages: generated by scripts/gen_church_pages.py -->"
SITEMAP_MARK_END = "  <!-- /church pages -->"

e = html.escape


def unsign(s):
    s = s.replace("đ", "d").replace("Đ", "D")
    s = unicodedata.normalize("NFD", s)
    s = "".join(c for c in s if unicodedata.category(c) != "Mn")
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


def assign_slugs(churches, registry):
    """Unique URL slugs: slug -> slug-province -> +district -> +id prefix.

    Churches already in the registry keep their published slug; only new ids get one.
    """
    churches = sorted(churches, key=lambda c: c["id"])
    taken = {r["slug"] for r in registry.values()}
    for c in churches:
        if c["id"] in registry:
            c["url_slug"] = registry[c["id"]]["slug"]
    candidates = [
        lambda c: c["slug"],
        lambda c: f'{c["slug"]}-{unsign(c["province"])}',
        lambda c: f'{c["slug"]}-{unsign(c["district"])}-{unsign(c["province"])}',
        lambda c: f'{c["slug"]}-{unsign(c["district"])}-{unsign(c["province"])}-{c["id"][:8]}',
    ]
    pending = [c for c in churches if "url_slug" not in c]
    for level, make in enumerate(candidates):
        groups = defaultdict(list)
        for c in pending:
            groups[re.sub(r"-+", "-", make(c)).strip("-")].append(c)
        pending = []
        for slug, members in groups.items():
            last = level == len(candidates) - 1
            if (len(members) == 1 and slug not in taken) or last:
                for c in members:
                    c["url_slug"] = slug if not last or slug not in taken else f'{slug}-{c["id"]}'
                    taken.add(c["url_slug"])
            else:
                pending.extend(members)
    slugs = [c["url_slug"] for c in churches]
    assert len(slugs) == len(set(slugs)), "duplicate url slugs"
    return churches


def update_registry(churches, registry):
    """Record slugs and bump lastmod only for churches whose data changed."""
    today = date.today().isoformat()
    for c in churches:
        digest = hashlib.sha1(json.dumps({k: v for k, v in c.items() if k != "url_slug"},
                                         ensure_ascii=False, sort_keys=True).encode()).hexdigest()[:16]
        prev = registry.get(c["id"])
        if not prev or prev["hash"] != digest:
            registry[c["id"]] = {"slug": c["url_slug"], "hash": digest, "lastmod": today}
        c["lastmod"] = registry[c["id"]]["lastmod"]
    REGISTRY.write_text(json.dumps(dict(sorted(registry.items())), ensure_ascii=False, indent=1) + "\n",
                        encoding="utf-8")


# Names that already say what kind of place it is; everything else is a parish ("Giáo xứ").
KIND_PREFIXES = ("giáo họ", "giáo xứ", "giáo điểm", "họ đạo", "chính tòa", "chính toà", "nhà thờ",
                 "nhà nguyện", "đền thánh", "tu viện", "đan viện", "trung tâm", "dòng ", "cộng đoàn",
                 "vương cung", "tiểu chủng")


PLACEHOLDER = "Chưa phân loại"  # backend's "unclassified district"; never show it


def clean(church):
    parts = [x.strip() for x in church["address"].split(",")]
    church["address"] = ", ".join(x for x in parts if x and x != PLACEHOLDER)
    if church["district"].strip() == PLACEHOLDER:
        church["district"] = ""
    return church


def full_name(church):
    """'Trinh Vương' -> 'Giáo xứ Trinh Vương', so searches like "giờ lễ giáo xứ trinh vương" match."""
    name = church["name"].strip()
    return name if name.lower().startswith(KIND_PREFIXES) else f"Giáo xứ {name}"


def times_for(church, key):
    raw = (church.get("schedule") or {}).get("weekly") or {}
    return sorted(t for t in raw.get(key) or [] if t)


def has_schedule(church):
    return any(times_for(church, k) for k, _ in DAYS)


def page_url(church):
    return f"{SITE}/nha-tho/{church['url_slug']}.html"


def maps_url(church):
    return f"https://www.google.com/maps/search/?api=1&query={church['latitude']},{church['longitude']}"


def describe(church):
    name, addr = full_name(church), church["address"]
    if name != church["name"]:
        name = f"{name} (nhà thờ {church['name']})"
    if has_schedule(church):
        sun = ", ".join(times_for(church, "0")) or "chưa cập nhật"
        week = ", ".join(times_for(church, "1")) or "chưa cập nhật"
        return (f"Giờ lễ {name}, {addr}. Chủ Nhật: {sun}. Ngày thường: {week}. "
                f"Xem lịch lễ cả tuần, chỉ đường và check-in đi lễ.")
    return f"Thông tin {name}, {addr}. Xem bản đồ chỉ đường và cập nhật giờ lễ trong ứng dụng Giờ Lễ & Lịch Công Giáo."


def json_ld(church):
    data = {
        "@context": "https://schema.org",
        "@type": "Church",
        "name": full_name(church),
        "alternateName": f"Nhà thờ {church['name']}",
        "url": page_url(church),
        "address": {
            "@type": "PostalAddress",
            "streetAddress": church["address"],
            "addressLocality": church["district"],
            "addressRegion": church["province"],
            "addressCountry": "VN",
        },
        "geo": {"@type": "GeoCoordinates", "latitude": church["latitude"], "longitude": church["longitude"]},
        "hasMap": maps_url(church),
    }
    if not church["district"]:
        del data["address"]["addressLocality"]
    if church.get("phone_number"):
        data["telephone"] = church["phone_number"]
    if church.get("photo"):
        data["image"] = church["photo"]
    crumbs = {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": "Trang chủ", "item": f"{SITE}/"},
            {"@type": "ListItem", "position": 2, "name": full_name(church), "item": page_url(church)},
        ],
    }
    dump = lambda d: json.dumps(d, ensure_ascii=False, indent=2).replace("</", "<\\/")
    return (f'<script type="application/ld+json">\n{dump(data)}\n</script>\n'
            f'<script type="application/ld+json">\n{dump(crumbs)}\n</script>')


# ── shared fragments ──────────────────────────────────────────────────────────

def load_template_parts():
    src = (ROOT / "index.html").read_text(encoding="utf-8")

    def between(start, end):
        i = src.index(start)
        j = src.index(end, i)
        return src[i:j + len(end)]

    css = between("<style>", "</style>")[len("<style>"):-len("</style>")]
    parts = {
        "hero_bg": between('<svg class="hero-bg"', "</svg>"),
        "logo": between('<svg viewBox="0 0 512 512"', "</svg>"),
        "phone": between('<div class="phone-wrap">', "</div>\n      </div>\n    </div>"),
        "features": between('<section class="features"', "</section>"),
        "how": between('<section class="how"', "</section>"),
        "script": between("<script>\n  (function", "</script>"),
    }
    # The phone-wrap slice ends one </div> past the phone-wrap itself; trim it back.
    parts["phone"] = parts["phone"][: parts["phone"].rindex("</div>")].rstrip()
    parts["phone"] = parts["phone"].replace('src="assets/', 'src="../assets/')
    return css, parts


EXTRA_CSS = """
/* ── CHURCH PAGES (generated) ── */
.crumbs { position: relative; z-index: 1; font-size: .85rem; color: var(--on-dark-dim); display: flex; flex-wrap: wrap; gap: 6px; }
.crumbs a:hover { color: var(--cream); }
.hero-addr { display: flex; gap: 10px; align-items: flex-start; font-size: 1.05rem; line-height: 1.55; color: var(--on-dark-dim); max-width: 46ch; }
.hero-addr svg { flex-shrink: 0; margin-top: 3px; }
@media (max-width: 960px) {
  .hero .phone-wrap { display: none; }
}
@media (max-width: 640px) {
  .brand { font-size: .95rem; }
  .hero-qr { display: none; }
}
"""

PIN_ICON = ('<svg width="20" height="20" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 22s-7-6.5-7-12a7 7 0 0 1 14 0c0 5.5-7 12-7 12z" '
            'fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path><circle cx="12" cy="10" r="2.5" fill="currentColor"></circle></svg>')
DL_ICON = ('<svg width="20" height="20" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 4v11 M7 10l5 5 5-5 M5 20h14" fill="none" stroke="#14492F" '
           'stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"></path></svg>')


def head(title, desc, canonical, extra="", noindex=False):
    return f"""<!DOCTYPE html>
<html lang="vi">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
{'<meta name="robots" content="noindex, follow">' + chr(10) if noindex else ""}<title>{e(title)}</title>
<meta name="description" content="{e(desc)}">
<link rel="canonical" href="{e(canonical)}">
<link rel="icon" href="../favicon.svg" type="image/svg+xml">
<meta property="og:type" content="website">
<meta property="og:site_name" content="Giờ Lễ &amp; Lịch Công Giáo">
<meta property="og:title" content="{e(title)}">
<meta property="og:description" content="{e(desc)}">
<meta property="og:url" content="{e(canonical)}">
<meta property="og:image" content="{SITE}/assets/og/og-image.png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:locale" content="vi_VN">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{e(title)}">
<meta name="twitter:description" content="{e(desc)}">
<meta name="twitter:image" content="{SITE}/assets/og/og-image.png">
{extra}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:wght@400;500;600;700;800&display=swap">
<link rel="stylesheet" href="../assets/church.css">
</head>
<body>
"""


def nav(parts):
    return f"""  <div class="wrap">
    <nav class="nav">
      <a class="brand" href="../index.html">
        {parts["logo"]}
        Giờ Lễ &amp; Lịch Công Giáo
      </a>
      <div class="nav-links">
        <a href="../index.html#tinh-nang">Tính năng</a>
      </div>
    </nav>
"""


def footer(parts):
    return f"""<section class="final-cta">
  <div class="wrap stagger">
    <h2>Xem giờ lễ mọi lúc trên điện thoại</h2>
    <p>Miễn phí trên Android. Tìm nhà thờ gần bạn, xem giờ lễ và check-in mỗi lần đi lễ.</p>
    <div class="cta-row">
      <div class="qr-card"><img src="../assets/qr/play-store.svg" alt="Mã QR tải Bước Theo Chân Chúa trên Google Play" width="216" height="216" loading="lazy"></div>
      <p class="qr-caption">Quét để cài đặt</p>
      <a class="btn" href="{PLAY_URL}" target="_blank" rel="noopener">
        {DL_ICON}
        Tải trên Google Play
      </a>
    </div>
  </div>
</section>

<footer class="site-footer">
  <div>© 2026 Giờ Lễ &amp; Lịch Công Giáo</div>
  <div class="links">
    <a href="../vn/privacy.html">Chính sách bảo mật</a>
    <a href="../vn/terms.html">Điều khoản sử dụng</a>
    <a href="mailto:support@thachnguyenhub.com">Liên hệ</a>
  </div>
</footer>

{parts["script"]}
</body>
</html>
"""


# ── church page ───────────────────────────────────────────────────────────────

def church_page(church, parts):
    name, addr = full_name(church), church["address"]
    title = f"Giờ Lễ {name} - {addr}"
    # Pages without mass times are thin: keep them out of Google until a schedule exists.
    out = head(title, describe(church), page_url(church), json_ld(church), noindex=not has_schedule(church))
    eyebrow = " · ".join(x for x in [church["district"], church["province"]] if x) or "Nhà thờ Công giáo"
    out += f"""
<header class="hero">
  {parts["hero_bg"]}
{nav(parts)}
    <div class="hero-grid">
      <div class="hero-copy">
        <nav class="crumbs" aria-label="Breadcrumb"><a href="../index.html">Trang chủ</a><span>›</span><span>{e(church["province"])}</span></nav>
        <span class="hero-eyebrow">{e(eyebrow)}</span>
        <h1>Giờ Lễ {e(name)}</h1>
        <p class="hero-addr">{PIN_ICON}<span>{e(addr)}</span></p>
        <div class="hero-actions">
          <a class="btn" href="{PLAY_URL}" target="_blank" rel="noopener">{DL_ICON} Tải ứng dụng để Xem giờ lễ</a>
          <a class="btn-outline" href="{e(maps_url(church))}" target="_blank" rel="noopener">Chỉ đường</a>
        </div>
        <div class="hero-qr">
          <img src="../assets/qr/play-store.svg" alt="Mã QR tải Bước Theo Chân Chúa trên Google Play" width="112" height="112" loading="lazy">
          <span>Quét mã QR để xem giờ lễ<br>và check-in trên điện thoại</span>
        </div>
      </div>
      {parts["phone"]}
    </div>
  </div>
</header>

{parts["features"]}

{parts["how"]}

"""
    out += footer(parts)
    return out


# ── sitemap ───────────────────────────────────────────────────────────────────

def update_sitemap(churches):
    path = ROOT / "sitemap.xml"
    xml = path.read_text(encoding="utf-8")
    if SITEMAP_MARK_START in xml:
        i = xml.index(SITEMAP_MARK_START)
        j = xml.index(SITEMAP_MARK_END) + len(SITEMAP_MARK_END)
        xml = xml[:i].rstrip() + "\n\n" + xml[j:].lstrip()
    entries = []
    for c in filter(has_schedule, churches):  # noindex pages stay out of the sitemap
        loc = f"{SITE}/nha-tho/{quote(c['url_slug'])}.html"
        entries.append(f"""  <url>
    <loc>{loc}</loc>
    <lastmod>{c["lastmod"]}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.6</priority>
  </url>""")
    block = SITEMAP_MARK_START + "\n" + "\n".join(entries) + "\n" + SITEMAP_MARK_END + "\n\n"
    xml = xml.replace("</urlset>", block + "</urlset>")
    path.write_text(xml, encoding="utf-8")


def main():
    churches = [clean(c) for c in json.loads((ROOT / "churches.json").read_text(encoding="utf-8"))]
    registry = json.loads(REGISTRY.read_text(encoding="utf-8")) if REGISTRY.exists() else {}
    churches = assign_slugs(churches, registry)
    update_registry(churches, registry)

    css, parts = load_template_parts()
    (ROOT / "assets" / "church.css").write_text(css.strip() + "\n" + EXTRA_CSS, encoding="utf-8")

    if OUT_DIR.exists():
        shutil.rmtree(OUT_DIR)
    OUT_DIR.mkdir()
    for c in churches:
        (OUT_DIR / f"{c['url_slug']}.html").write_text(church_page(c, parts), encoding="utf-8")

    update_sitemap(churches)
    written = len(list(OUT_DIR.glob("*.html")))
    assert written == len(churches), (written, len(churches))
    print(f"wrote {written} church pages, sitemap updated")


if __name__ == "__main__":
    main()
